### ISSUE TITLE
comentarios avances 3 y README

### ISSUE THREAD

**Issue by AliciaMstt** [IsauraRReinhold/Proyecto-trascriptoma_flores#2]
Muy bien :)

No queda claro que la referencia que pones es el orgien de los datos. Especifica. 

"All the analysis described below were run in Ubuntu 14.06." mueve esto a la sección Scripts. 

En "Scripts" pon el nombre de cada uno de los scripts y especifica qué es lo que hace cada uno, en el orden que deben correrse

**Comment by IsauraRReinhold** [comment]
Ok, gracias 
Saludos
